In [2]:
416//{0:32, 1:16, 2:8}[2]

52

In [1]:
import numpy as np

In [17]:
tmp = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], dtype=np.float)

In [41]:
tmp

array([[ 1.,  2.,  3.,  4.],
       [ 5.,  6.,  7.,  8.],
       [ 9., 10., 11., 12.]])

In [40]:
tmp[::-1]

array([[ 9., 10., 11., 12.],
       [ 5.,  6.,  7.,  8.],
       [ 1.,  2.,  3.,  4.]])

In [33]:
import keras 
from keras import backend as K
import tensorflow as tf

In [38]:
with tf.Session() as sess:
    
    grid_y = K.tile(K.reshape(K.arange(0, stop=10), [-1, 1, 1, 1]),
        [1, 10, 1, 1])
    grid_x = K.tile(K.reshape(K.arange(0, stop=10), [1, -1, 1, 1]),
        [10, 1, 1, 1])
    grid = K.concatenate([grid_x, grid_y])
    print(grid)

Tensor("concat_1:0", shape=(10, 10, 1, 2), dtype=int32)


In [31]:
K.Print(grid_y, message='y_true = ')

AttributeError: module 'keras.backend' has no attribute 'Print'

In [25]:
grid_x

<tf.Tensor 'Tile_1:0' shape=(10, 10, 1, 1) dtype=int32>

In [2]:
a = np.array([[[1,2,3],[4,5,6]]])
print(a.shape)
# 1,2,3
d = np.expand_dims(a,-2)

print(d.shape)
d

(1, 2, 3)
(1, 2, 1, 3)


array([[[[1, 2, 3]],

        [[4, 5, 6]]]])

In [7]:
tmp1 = np.zeros((1,1,2))
tmp2 = np.zeros((1,2,2))

tmp1[0][0][0] = 1
tmp2[0][0][1] = 1

tmp = np.maximum(tmp1,tmp2)
tmp

array([[[1., 1.],
        [1., 0.]]])

In [52]:
boxes_wh = np.zeros((2,2))
boxes_wh[1][1] = 1
boxes_wh[1][0] = 1

tmp = boxes_wh[..., 0]>0
tmp

array([False,  True])

In [53]:
boxes_wh[..., 0]

array([0., 1.])

In [54]:
boxes_wh

array([[0., 0.],
       [1., 1.]])